M48
; DRILL file KiCad 10.0.3 date 2026-09-03T16:17:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-03T16:17:30+06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X102.61Y-114.9
X108.39Y-114.9
T2
X114.5Y-106.83
X117.5Y-106.83
M30
